// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TesisGestorApi.Data;

#nullable disable

namespace TesisGestorApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505120000_AddRolSecretario")]
    partial class AddRolSecretario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Modelo snapshot gestionado por ApplicationDbContextModelSnapshot.cs
        }
    }
}
