// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesisGestorApi.Data;

#nullable disable

namespace TesisGestorApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310030928_FeatUmbralNotificaciones")]
    partial class FeatUmbralNotificaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TesisGestorApi.Entities.Anio", b =>
                {
                    b.Property<Guid>("IdAnio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("IdAnio");

                    b.ToTable("Anios");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Asistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EstudianteIdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("HoraEntradaManana")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HoraEntradaTarde")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HoraSalidaManana")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HoraSalidaTarde")
                        .HasColumnType("interval");

                    b.Property<Guid?>("TipoManianaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TipoTardeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorTotalInasistencia")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.HasIndex("TipoManianaId");

                    b.HasIndex("TipoTardeId");

                    b.HasIndex("EstudianteId", "Fecha")
                        .IsUnique();

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaPorEspacio", b =>
                {
                    b.Property<Guid>("IdAsistenciaEspacio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("IdClaseDictada")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.HasKey("IdAsistenciaEspacio");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdClaseDictada", "IdEstudiante")
                        .IsUnique();

                    b.ToTable("AsistenciasPorEspacio");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaResumenAnual", b =>
                {
                    b.Property<Guid>("IdResumen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnioLectivo")
                        .HasColumnType("integer");

                    b.Property<decimal>("FaltasAcumuladas")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("FechaTeaGeneralUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<bool>("TeaGeneral")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UltimoRecalculoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdResumen");

                    b.HasIndex("IdEstudiante", "AnioLectivo")
                        .IsUnique();

                    b.ToTable("AsistenciaResumenAnual", (string)null);
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaUmbralNotificacion", b =>
                {
                    b.Property<Guid>("IdNotif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnioLectivo")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadEnviados")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProximoEnvioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoEnvioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UltimoError")
                        .HasColumnType("text");

                    b.Property<int>("Umbral")
                        .HasColumnType("integer");

                    b.HasKey("IdNotif");

                    b.HasIndex("Estado", "ProximoEnvioUtc");

                    b.HasIndex("IdEstudiante", "AnioLectivo", "Umbral")
                        .IsUnique();

                    b.ToTable("AsistenciaUmbralNotificacion", (string)null);
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ClaseDictada", b =>
                {
                    b.Property<Guid>("IdClaseDictada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Dictada")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("IdEC")
                        .HasColumnType("uuid");

                    b.Property<string>("Tema")
                        .HasColumnType("text");

                    b.HasKey("IdClaseDictada");

                    b.HasIndex("IdEC", "Fecha");

                    b.ToTable("ClasesDictadas");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.CredencialQR", b =>
                {
                    b.Property<Guid>("IdQR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AñoLectivo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Codigo")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enviado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EstudianteIdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.HasKey("IdQR");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.ToTable("CredencialesQR");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Curricula", b =>
                {
                    b.Property<Guid>("IdCurricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsContraturno")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCurricula");

                    b.ToTable("Curriculas");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Curso", b =>
                {
                    b.Property<Guid>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AñoLectivo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdAnio")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdDivision")
                        .HasColumnType("uuid");

                    b.HasKey("IdCurso");

                    b.HasIndex("IdAnio");

                    b.HasIndex("IdDivision");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.DetalleCursado", b =>
                {
                    b.Property<Guid>("IdCursado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.HasKey("IdCursado");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("DetallesCursado");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Division", b =>
                {
                    b.Property<Guid>("IdDivision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<char>("Nombre")
                        .HasColumnType("character(1)");

                    b.HasKey("IdDivision");

                    b.ToTable("Divisiones");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Docente", b =>
                {
                    b.Property<Guid>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDocente");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.EspacioCurricular", b =>
                {
                    b.Property<Guid>("IdEC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCurricula")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdDocente")
                        .HasColumnType("uuid");

                    b.HasKey("IdEC");

                    b.HasIndex("IdCurricula");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdDocente");

                    b.ToTable("EspaciosCurriculares");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Estudiante", b =>
                {
                    b.Property<Guid>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<bool>("TeaGeneral")
                        .HasColumnType("boolean");

                    b.HasKey("IdEstudiante");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Horario", b =>
                {
                    b.Property<Guid>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DíaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HorarioEntrada")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HorarioSalida")
                        .HasColumnType("interval");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEC")
                        .HasColumnType("uuid");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdEC");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Preceptor", b =>
                {
                    b.Property<Guid>("IdPreceptor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CursoIdCurso")
                        .HasColumnType("uuid");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPreceptor");

                    b.HasIndex("CursoIdCurso");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Preceptores");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.RetiroAnticipado", b =>
                {
                    b.Property<Guid>("IdRetiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ConReingreso")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EstudianteIdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("HorarioReingreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HorarioRetiro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdAsistencia")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdTutor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorIdTutor")
                        .HasColumnType("uuid");

                    b.HasKey("IdRetiro");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.HasIndex("IdAsistencia")
                        .IsUnique();

                    b.HasIndex("TutorIdTutor");

                    b.ToTable("RetirosAnticipados");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Rol", b =>
                {
                    b.Property<Guid>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.TipoAsistencia", b =>
                {
                    b.Property<Guid>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("numeric");

                    b.HasKey("IdTipo");

                    b.ToTable("TiposAsistencia");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Tutor", b =>
                {
                    b.Property<Guid>("IdTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelacionEstudiante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Telefono")
                        .HasColumnType("integer");

                    b.HasKey("IdTutor");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.TutorEstudiante", b =>
                {
                    b.Property<Guid>("IdTutor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.HasKey("IdTutor", "IdEstudiante");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("TutorEstudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Verificado")
                        .HasColumnType("boolean");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.UsuarioRol", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uuid");

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Asistencia", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Estudiante", null)
                        .WithMany("Asistencias")
                        .HasForeignKey("EstudianteIdEstudiante");

                    b.HasOne("TesisGestorApi.Entities.TipoAsistencia", "TipoManiana")
                        .WithMany()
                        .HasForeignKey("TipoManianaId");

                    b.HasOne("TesisGestorApi.Entities.TipoAsistencia", "TipoTarde")
                        .WithMany()
                        .HasForeignKey("TipoTardeId");

                    b.Navigation("Estudiante");

                    b.Navigation("TipoManiana");

                    b.Navigation("TipoTarde");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaPorEspacio", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.ClaseDictada", "ClaseDictada")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdClaseDictada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany("AsistenciasPorEspacio")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaseDictada");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaResumenAnual", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaUmbralNotificacion", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ClaseDictada", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.EspacioCurricular", "EspacioCurricular")
                        .WithMany("ClasesDictadas")
                        .HasForeignKey("IdEC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EspacioCurricular");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.CredencialQR", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteIdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Curso", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Anio", "Anio")
                        .WithMany("Cursos")
                        .HasForeignKey("IdAnio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Division", "Division")
                        .WithMany("Cursos")
                        .HasForeignKey("IdDivision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anio");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.DetalleCursado", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Curso", "Curso")
                        .WithMany("DetallesCursado")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany("DetallesCursado")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Docente", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Usuario", "Usuario")
                        .WithOne("Docente")
                        .HasForeignKey("TesisGestorApi.Entities.Docente", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.EspacioCurricular", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Curricula", "Curricula")
                        .WithMany("EspaciosCurriculares")
                        .HasForeignKey("IdCurricula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Curso", "Curso")
                        .WithMany("EspaciosCurriculares")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Docente", "Docente")
                        .WithMany("EspaciosCurriculares")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curricula");

                    b.Navigation("Curso");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Horario", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Curso", "Curso")
                        .WithMany("Horarios")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.EspacioCurricular", "EspacioCurricular")
                        .WithMany("Horarios")
                        .HasForeignKey("IdEC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("EspacioCurricular");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Preceptor", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Curso", "Curso")
                        .WithMany("Preceptores")
                        .HasForeignKey("CursoIdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Usuario", "Usuario")
                        .WithOne("Preceptor")
                        .HasForeignKey("TesisGestorApi.Entities.Preceptor", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.RetiroAnticipado", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany("RetirosAnticipados")
                        .HasForeignKey("EstudianteIdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Asistencia", "Asistencia")
                        .WithOne()
                        .HasForeignKey("TesisGestorApi.Entities.RetiroAnticipado", "IdAsistencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Tutor", "Tutor")
                        .WithMany("RetirosAnticipados")
                        .HasForeignKey("TutorIdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asistencia");

                    b.Navigation("Estudiante");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.TutorEstudiante", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany("TutorEstudiantes")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Tutor", "Tutor")
                        .WithMany("TutorEstudiantes")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.UsuarioRol", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Anio", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ClaseDictada", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Curricula", b =>
                {
                    b.Navigation("EspaciosCurriculares");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Curso", b =>
                {
                    b.Navigation("DetallesCursado");

                    b.Navigation("EspaciosCurriculares");

                    b.Navigation("Horarios");

                    b.Navigation("Preceptores");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Division", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Docente", b =>
                {
                    b.Navigation("EspaciosCurriculares");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.EspacioCurricular", b =>
                {
                    b.Navigation("ClasesDictadas");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Estudiante", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("AsistenciasPorEspacio");

                    b.Navigation("DetallesCursado");

                    b.Navigation("RetirosAnticipados");

                    b.Navigation("TutorEstudiantes");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Tutor", b =>
                {
                    b.Navigation("RetirosAnticipados");

                    b.Navigation("TutorEstudiantes");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Usuario", b =>
                {
                    b.Navigation("Docente");

                    b.Navigation("Preceptor");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
