// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TesisGestorApi.Data;

#nullable disable

namespace TesisGestorApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414230851_DosRetirosPorDia")]
    partial class DosRetirosPorDia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Modelo snapshot gestionado por ApplicationDbContextModelSnapshot.cs
        }
    }
}
