// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesisGestorApi.Data;

#nullable disable

namespace TesisGestorApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RepoDB.Entities.ComentarioParte", b =>
                {
                    b.Property<Guid>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdParte")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("IdComentario");

                    b.HasIndex("IdParte");

                    b.ToTable("ComentariosParte");
                });

            modelBuilder.Entity("RepoDB.Entities.ParteDiario", b =>
                {
                    b.Property<Guid>("IdParte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.HasKey("IdParte");

                    b.HasIndex("IdCurso", "Fecha")
                        .IsUnique();

                    b.ToTable("PartesDiarios");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Anio", b =>
                {
                    b.Property<Guid>("IdAnio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("IdAnio");

                    b.ToTable("Anios");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ArchivoIE", b =>
                {
                    b.Property<Guid>("IdArchivoIE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Habilitada")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("IdArchivoIEAnterior")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdIE")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuarioCarga")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("TipoCalificacion")
                        .HasColumnType("integer");

                    b.Property<int>("TipoIE")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("IdArchivoIE");

                    b.HasIndex("IdArchivoIEAnterior");

                    b.HasIndex("IdUsuarioCarga");

                    b.HasIndex("IdIE", "TipoCalificacion")
                        .IsUnique()
                        .HasFilter("\"Habilitada\" = TRUE");

                    b.HasIndex("IdIE", "TipoCalificacion", "FechaCarga");

                    b.ToTable("ArchivoIE", (string)null);
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ArchivoIEBloquePrograma", b =>
                {
                    b.Property<Guid>("IdArchivoIE")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdBloquePrograma")
                        .HasColumnType("uuid");

                    b.HasKey("IdArchivoIE", "IdBloquePrograma");

                    b.HasIndex("IdBloquePrograma");

                    b.ToTable("ArchivoIEBloquePrograma", (string)null);
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Asistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EstudianteIdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("HoraEntradaManana")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HoraEntradaTarde")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HoraSalidaManana")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HoraSalidaTarde")
                        .HasColumnType("interval");

                    b.Property<Guid?>("TipoLlegadaManianaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TipoManianaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TipoTardeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorTotalInasistencia")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.HasIndex("TipoLlegadaManianaId");

                    b.HasIndex("TipoManianaId");

                    b.HasIndex("TipoTardeId");

                    b.HasIndex("EstudianteId", "Fecha")
                        .IsUnique();

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaPorEspacio", b =>
                {
                    b.Property<Guid>("IdAsistenciaEspacio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("IdClaseDictada")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.HasKey("IdAsistenciaEspacio");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdClaseDictada", "IdEstudiante")
                        .IsUnique();

                    b.ToTable("AsistenciasPorEspacio");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaResumenAnual", b =>
                {
                    b.Property<Guid>("IdResumen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnioLectivo")
                        .HasColumnType("integer");

                    b.Property<decimal>("FaltasAcumuladas")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("FechaTeaGeneralUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<bool>("TeaGeneral")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UltimoRecalculoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdResumen");

                    b.HasIndex("IdEstudiante", "AnioLectivo")
                        .IsUnique();

                    b.ToTable("AsistenciaResumenAnual", (string)null);
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaUmbralNotificacion", b =>
                {
                    b.Property<Guid>("IdNotif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnioLectivo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<int>("Umbral")
                        .HasColumnType("integer");

                    b.HasKey("IdNotif");

                    b.HasIndex("IdEstudiante", "AnioLectivo", "Umbral")
                        .IsUnique();

                    b.ToTable("AsistenciaUmbralNotificacion", (string)null);
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AuditoriaAsistenciaEC", b =>
                {
                    b.Property<Guid>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("EstadoAnterior")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstadoNuevo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HorarioEvento")
                        .HasColumnType("interval");

                    b.Property<Guid>("IdClaseDictada")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdClaseDictada");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdEstudiante", "IdClaseDictada", "FechaRegistro");

                    b.ToTable("AuditoriasAsistenciaEC");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AuditoriaCalificacionDetalle", b =>
                {
                    b.Property<Guid>("IdDetalleAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdCalificacionAnterior")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCalificacionNueva")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdIE")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionAuditoria")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoCalificacion")
                        .HasColumnType("integer");

                    b.Property<int?>("ValorAnterior")
                        .HasColumnType("integer");

                    b.Property<int?>("ValorNuevo")
                        .HasColumnType("integer");

                    b.HasKey("IdDetalleAuditoria");

                    b.HasIndex("IdCalificacionAnterior");

                    b.HasIndex("IdCalificacionNueva");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdSesionAuditoria");

                    b.HasIndex("IdIE", "IdEstudiante");

                    b.ToTable("AuditoriaCalificacionDetalle", (string)null);
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AuditoriaCalificacionSesion", b =>
                {
                    b.Property<Guid>("IdSesionAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEC")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<int>("Origen")
                        .HasColumnType("integer");

                    b.HasKey("IdSesionAuditoria");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdEC", "FechaRegistro");

                    b.ToTable("AuditoriaCalificacionSesion", (string)null);
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AuditoriaEventoInstitucional", b =>
                {
                    b.Property<Guid>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEvento")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoOperacion")
                        .HasColumnType("integer");

                    b.Property<string>("ValoresAnteriores")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ValoresNuevos")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdUsuario");

                    b.ToTable("AuditoriasEventosInstitucionales");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.BloquePrograma", b =>
                {
                    b.Property<Guid>("IdBloquePrograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdPrograma")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdTema")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUnidad")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("IdBloquePrograma");

                    b.HasIndex("IdPrograma");

                    b.HasIndex("IdTema");

                    b.HasIndex("IdUnidad");

                    b.ToTable("BloquesProgramas");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Calificacion", b =>
                {
                    b.Property<Guid>("IdCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Habilitada")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdArchivoIE")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdCalificacionAnterior")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdIE")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuarioCarga")
                        .HasColumnType("uuid");

                    b.Property<int>("Origen")
                        .HasColumnType("integer");

                    b.Property<int?>("Puntaje")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCalificacion")
                        .HasColumnType("integer");

                    b.HasKey("IdCalificacion");

                    b.HasIndex("IdArchivoIE");

                    b.HasIndex("IdCalificacionAnterior");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdUsuarioCarga");

                    b.HasIndex("IdIE", "IdEstudiante");

                    b.HasIndex("IdIE", "TipoCalificacion");

                    b.HasIndex("IdIE", "IdEstudiante", "TipoCalificacion")
                        .IsUnique()
                        .HasFilter("\"Habilitada\" = TRUE");

                    b.ToTable("Calificacion", (string)null);
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ClaseBloquePrograma", b =>
                {
                    b.Property<Guid>("IdClasePlanificacion")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdBloquePrograma")
                        .HasColumnType("uuid");

                    b.HasKey("IdClasePlanificacion", "IdBloquePrograma");

                    b.HasIndex("IdBloquePrograma");

                    b.ToTable("ClasesBloquesProgramas");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ClaseDictada", b =>
                {
                    b.Property<Guid>("IdClaseDictada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Dictada")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("HorarioEntradaEfectiva")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HorarioSalidaEfectiva")
                        .HasColumnType("interval");

                    b.Property<Guid>("IdEC")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdHorario")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<string>("Tema")
                        .HasColumnType("text");

                    b.HasKey("IdClaseDictada");

                    b.HasIndex("IdEC", "Fecha");

                    b.HasIndex("IdHorario", "Fecha")
                        .IsUnique();

                    b.ToTable("ClasesDictadas");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.CredencialQR", b =>
                {
                    b.Property<Guid>("IdQR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AñoLectivo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Codigo")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enviado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EstudianteIdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.HasKey("IdQR");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.ToTable("CredencialesQR");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Curricula", b =>
                {
                    b.Property<Guid>("IdCurricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsContraturno")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCurricula");

                    b.ToTable("Curriculas");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Curso", b =>
                {
                    b.Property<Guid>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AñoLectivo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdAnio")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdDivision")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdPreceptor")
                        .HasColumnType("uuid");

                    b.HasKey("IdCurso");

                    b.HasIndex("IdAnio");

                    b.HasIndex("IdDivision");

                    b.HasIndex("IdPreceptor");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.DetalleCursado", b =>
                {
                    b.Property<Guid>("IdCursado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.HasKey("IdCursado");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("DetallesCursado");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Division", b =>
                {
                    b.Property<Guid>("IdDivision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<char>("Nombre")
                        .HasColumnType("character(1)");

                    b.HasKey("IdDivision");

                    b.ToTable("Divisiones");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Docente", b =>
                {
                    b.Property<Guid>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.HasKey("IdDocente");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.DocenteEspacioCurricular", b =>
                {
                    b.Property<Guid>("IdDocenteEC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdDocente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEC")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.HasKey("IdDocenteEC");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdEC");

                    b.ToTable("DocentesEspaciosCurriculares");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.EspacioCurricular", b =>
                {
                    b.Property<Guid>("IdEC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCurricula")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdDocente")
                        .HasColumnType("uuid");

                    b.HasKey("IdEC");

                    b.HasIndex("IdCurricula");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdDocente");

                    b.ToTable("EspaciosCurriculares");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Estudiante", b =>
                {
                    b.Property<Guid>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Domicilio")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoEstudiante")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<bool>("TeaGeneral")
                        .HasColumnType("boolean");

                    b.HasKey("IdEstudiante");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.EventoInstitucional", b =>
                {
                    b.Property<Guid>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AnioLectivo")
                        .HasColumnType("integer");

                    b.Property<bool>("CambioActividad")
                        .HasColumnType("boolean");

                    b.Property<string>("ComentarioCambioActividad")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("ContabilizaAsistencia")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdUsuarioCreacion")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("IdEvento");

                    b.HasIndex("IdUsuarioCreacion");

                    b.HasIndex("AnioLectivo", "Activo");

                    b.ToTable("EventosInstitucionales");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.EventoInstitucionalCurso", b =>
                {
                    b.Property<Guid>("IdEvento")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.HasKey("IdEvento", "IdCurso");

                    b.HasIndex("IdCurso");

                    b.ToTable("EventosInstitucionalCursos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Horario", b =>
                {
                    b.Property<Guid>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DíaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HorarioEntrada")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HorarioSalida")
                        .HasColumnType("interval");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEC")
                        .HasColumnType("uuid");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdEC");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.InstanciaEvaluativa", b =>
                {
                    b.Property<Guid>("IdIE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEC")
                        .HasColumnType("uuid");

                    b.Property<int>("Nro")
                        .HasColumnType("integer");

                    b.HasKey("IdIE");

                    b.HasIndex("IdEC", "Nro")
                        .IsUnique();

                    b.ToTable("InstanciaEvaluativa", (string)null);
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ObjetivoPrograma", b =>
                {
                    b.Property<Guid>("IdObjetivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("IdPrograma")
                        .HasColumnType("uuid");

                    b.Property<int>("Nro")
                        .HasColumnType("integer");

                    b.HasKey("IdObjetivo");

                    b.HasIndex("IdPrograma");

                    b.ToTable("ObjetivosPrograma");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Permiso", b =>
                {
                    b.Property<Guid>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Planificacion", b =>
                {
                    b.Property<Guid>("IdPlanificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaHasta")
                        .HasColumnType("date");

                    b.Property<Guid>("IdDocente")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IdPlanificacion");

                    b.HasIndex("IdDocente");

                    b.ToTable("Planificaciones");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Preceptor", b =>
                {
                    b.Property<Guid>("IdPreceptor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EsDelegado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.HasKey("IdPreceptor");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Preceptores");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.PreceptorCurso", b =>
                {
                    b.Property<Guid>("IdPreceptorCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPreceptor")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.HasKey("IdPreceptorCurso");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdPreceptor");

                    b.ToTable("PreceptoresCursos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Programa", b =>
                {
                    b.Property<Guid>("IdPrograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnioLectivo")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("HorasCatedra")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdDocente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEC")
                        .HasColumnType("uuid");

                    b.Property<int>("Origen")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IdPrograma");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdEC", "AnioLectivo")
                        .IsUnique();

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<bool>("Revocado")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.RetiroAnticipado", b =>
                {
                    b.Property<Guid>("IdRetiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApellidoResponsable")
                        .HasColumnType("text");

                    b.Property<bool>("ConReingreso")
                        .HasColumnType("boolean");

                    b.Property<string>("CorreoResponsable")
                        .HasColumnType("text");

                    b.Property<string>("DNIResponsable")
                        .HasColumnType("text");

                    b.Property<Guid?>("EstudianteIdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("HorarioLimiteReingreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HorarioReingreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HorarioRetiro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdAsistencia")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdTutor")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombrePreceptor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreResponsable")
                        .HasColumnType("text");

                    b.Property<string>("RelacionResponsable")
                        .HasColumnType("text");

                    b.Property<string>("TelefonoResponsable")
                        .HasColumnType("text");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRetiro");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdTutor");

                    b.HasIndex("IdAsistencia", "Turno")
                        .IsUnique();

                    b.ToTable("RetirosAnticipados");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Rol", b =>
                {
                    b.Property<Guid>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.RolPermiso", b =>
                {
                    b.Property<Guid>("IdRolPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPermiso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uuid");

                    b.HasKey("IdRolPermiso");

                    b.HasIndex("IdPermiso");

                    b.HasIndex("IdRol", "IdPermiso")
                        .IsUnique();

                    b.ToTable("RolPermisos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Tema", b =>
                {
                    b.Property<Guid>("IdTema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdUnidad")
                        .HasColumnType("uuid");

                    b.Property<int>("Nro")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("IdTema");

                    b.HasIndex("IdUnidad");

                    b.ToTable("Temas");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.TipoAsistencia", b =>
                {
                    b.Property<Guid>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("numeric");

                    b.HasKey("IdTipo");

                    b.ToTable("TiposAsistencia");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Tutor", b =>
                {
                    b.Property<Guid>("IdTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Domicilio")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUltimaNotificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelacionEstudiante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.HasKey("IdTutor");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.TutorEstudiante", b =>
                {
                    b.Property<Guid>("IdTutor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.HasKey("IdTutor", "IdEstudiante");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("TutorEstudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Unidad", b =>
                {
                    b.Property<Guid>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdPrograma")
                        .HasColumnType("uuid");

                    b.Property<int>("Nro")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("IdUnidad");

                    b.HasIndex("IdPrograma");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimientoContrasena")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntentosFailidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiereCambioContrasena")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.UsuarioRol", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uuid");

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("RepoDB.Entities.ComentarioParte", b =>
                {
                    b.HasOne("RepoDB.Entities.ParteDiario", "ParteDiario")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdParte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParteDiario");
                });

            modelBuilder.Entity("RepoDB.Entities.ParteDiario", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ArchivoIE", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.ArchivoIE", "ArchivoAnterior")
                        .WithMany("VersionesSiguientes")
                        .HasForeignKey("IdArchivoIEAnterior")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TesisGestorApi.Entities.InstanciaEvaluativa", "InstanciaEvaluativa")
                        .WithMany("Archivos")
                        .HasForeignKey("IdIE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Usuario", "UsuarioCarga")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCarga")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArchivoAnterior");

                    b.Navigation("InstanciaEvaluativa");

                    b.Navigation("UsuarioCarga");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ArchivoIEBloquePrograma", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.ArchivoIE", "ArchivoIE")
                        .WithMany("BloquesPrograma")
                        .HasForeignKey("IdArchivoIE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.BloquePrograma", "BloquePrograma")
                        .WithMany("ArchivosIE")
                        .HasForeignKey("IdBloquePrograma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivoIE");

                    b.Navigation("BloquePrograma");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Asistencia", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Estudiante", null)
                        .WithMany("Asistencias")
                        .HasForeignKey("EstudianteIdEstudiante");

                    b.HasOne("TesisGestorApi.Entities.TipoAsistencia", "TipoLlegadaManiana")
                        .WithMany()
                        .HasForeignKey("TipoLlegadaManianaId");

                    b.HasOne("TesisGestorApi.Entities.TipoAsistencia", "TipoManiana")
                        .WithMany()
                        .HasForeignKey("TipoManianaId");

                    b.HasOne("TesisGestorApi.Entities.TipoAsistencia", "TipoTarde")
                        .WithMany()
                        .HasForeignKey("TipoTardeId");

                    b.Navigation("Estudiante");

                    b.Navigation("TipoLlegadaManiana");

                    b.Navigation("TipoManiana");

                    b.Navigation("TipoTarde");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaPorEspacio", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.ClaseDictada", "ClaseDictada")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdClaseDictada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany("AsistenciasPorEspacio")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaseDictada");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaResumenAnual", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AsistenciaUmbralNotificacion", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AuditoriaAsistenciaEC", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.ClaseDictada", "ClaseDictada")
                        .WithMany()
                        .HasForeignKey("IdClaseDictada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaseDictada");

                    b.Navigation("Estudiante");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AuditoriaCalificacionDetalle", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Calificacion", "CalificacionAnterior")
                        .WithMany()
                        .HasForeignKey("IdCalificacionAnterior")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TesisGestorApi.Entities.Calificacion", "CalificacionNueva")
                        .WithMany()
                        .HasForeignKey("IdCalificacionNueva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.InstanciaEvaluativa", "InstanciaEvaluativa")
                        .WithMany()
                        .HasForeignKey("IdIE")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.AuditoriaCalificacionSesion", "Sesion")
                        .WithMany("Detalles")
                        .HasForeignKey("IdSesionAuditoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalificacionAnterior");

                    b.Navigation("CalificacionNueva");

                    b.Navigation("Estudiante");

                    b.Navigation("InstanciaEvaluativa");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AuditoriaCalificacionSesion", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.EspacioCurricular", "EspacioCurricular")
                        .WithMany()
                        .HasForeignKey("IdEC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EspacioCurricular");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AuditoriaEventoInstitucional", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.EventoInstitucional", "EventoInstitucional")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventoInstitucional");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.BloquePrograma", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Programa", "Programa")
                        .WithMany()
                        .HasForeignKey("IdPrograma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Tema", "Tema")
                        .WithMany()
                        .HasForeignKey("IdTema")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TesisGestorApi.Entities.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Programa");

                    b.Navigation("Tema");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Calificacion", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.ArchivoIE", "ArchivoIE")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdArchivoIE")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Calificacion", "CalificacionAnterior")
                        .WithMany("VersionesSiguientes")
                        .HasForeignKey("IdCalificacionAnterior")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.InstanciaEvaluativa", "InstanciaEvaluativa")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdIE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Usuario", "UsuarioCarga")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCarga")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArchivoIE");

                    b.Navigation("CalificacionAnterior");

                    b.Navigation("Estudiante");

                    b.Navigation("InstanciaEvaluativa");

                    b.Navigation("UsuarioCarga");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ClaseBloquePrograma", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.BloquePrograma", "BloquePrograma")
                        .WithMany("ClasesBloquePrograma")
                        .HasForeignKey("IdBloquePrograma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Planificacion", "Planificacion")
                        .WithMany("ClasesBloquePrograma")
                        .HasForeignKey("IdClasePlanificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloquePrograma");

                    b.Navigation("Planificacion");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ClaseDictada", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.EspacioCurricular", "EspacioCurricular")
                        .WithMany("ClasesDictadas")
                        .HasForeignKey("IdEC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Horario", "Horario")
                        .WithMany("ClasesDictadas")
                        .HasForeignKey("IdHorario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EspacioCurricular");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.CredencialQR", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteIdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Curso", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Anio", "Anio")
                        .WithMany("Cursos")
                        .HasForeignKey("IdAnio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Division", "Division")
                        .WithMany("Cursos")
                        .HasForeignKey("IdDivision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Preceptor", "Preceptor")
                        .WithMany("Cursos")
                        .HasForeignKey("IdPreceptor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Anio");

                    b.Navigation("Division");

                    b.Navigation("Preceptor");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.DetalleCursado", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Curso", "Curso")
                        .WithMany("DetallesCursado")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany("DetallesCursado")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Docente", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Usuario", "Usuario")
                        .WithOne("Docente")
                        .HasForeignKey("TesisGestorApi.Entities.Docente", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.DocenteEspacioCurricular", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Docente", "Docente")
                        .WithMany("DocentesEspaciosCurriculares")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.EspacioCurricular", "EspacioCurricular")
                        .WithMany("DocentesEspaciosCurriculares")
                        .HasForeignKey("IdEC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("EspacioCurricular");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.EspacioCurricular", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Curricula", "Curricula")
                        .WithMany("EspaciosCurriculares")
                        .HasForeignKey("IdCurricula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Curso", "Curso")
                        .WithMany("EspaciosCurriculares")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Docente", "Docente")
                        .WithMany("EspaciosCurriculares")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Curricula");

                    b.Navigation("Curso");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.EventoInstitucional", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.EventoInstitucionalCurso", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.EventoInstitucional", "EventoInstitucional")
                        .WithMany("Cursos")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("EventoInstitucional");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Horario", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Curso", "Curso")
                        .WithMany("Horarios")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.EspacioCurricular", "EspacioCurricular")
                        .WithMany("Horarios")
                        .HasForeignKey("IdEC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("EspacioCurricular");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.InstanciaEvaluativa", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.EspacioCurricular", "EspacioCurricular")
                        .WithMany("InstanciasEvaluativas")
                        .HasForeignKey("IdEC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EspacioCurricular");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ObjetivoPrograma", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Programa", "Programa")
                        .WithMany("Objetivos")
                        .HasForeignKey("IdPrograma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Planificacion", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Preceptor", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Usuario", "Usuario")
                        .WithOne("Preceptor")
                        .HasForeignKey("TesisGestorApi.Entities.Preceptor", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.PreceptorCurso", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Curso", "Curso")
                        .WithMany("PreceptoresCursos")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Preceptor", "Preceptor")
                        .WithMany("PreceptoresCursos")
                        .HasForeignKey("IdPreceptor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Preceptor");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Programa", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.EspacioCurricular", "EspacioCurricular")
                        .WithMany()
                        .HasForeignKey("IdEC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Docente");

                    b.Navigation("EspacioCurricular");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.RefreshToken", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.RetiroAnticipado", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", null)
                        .WithMany("RetirosAnticipados")
                        .HasForeignKey("EstudianteIdEstudiante");

                    b.HasOne("TesisGestorApi.Entities.Asistencia", "Asistencia")
                        .WithMany()
                        .HasForeignKey("IdAsistencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Tutor", "Tutor")
                        .WithMany("RetirosAnticipados")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asistencia");

                    b.Navigation("Estudiante");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.RolPermiso", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Tema", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Unidad", "Unidad")
                        .WithMany("Temas")
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.TutorEstudiante", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Estudiante", "Estudiante")
                        .WithMany("TutorEstudiantes")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Tutor", "Tutor")
                        .WithMany("TutorEstudiantes")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Unidad", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Programa", "Programa")
                        .WithMany("Unidades")
                        .HasForeignKey("IdPrograma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.UsuarioRol", b =>
                {
                    b.HasOne("TesisGestorApi.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisGestorApi.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RepoDB.Entities.ParteDiario", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Anio", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ArchivoIE", b =>
                {
                    b.Navigation("BloquesPrograma");

                    b.Navigation("Calificaciones");

                    b.Navigation("VersionesSiguientes");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.AuditoriaCalificacionSesion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.BloquePrograma", b =>
                {
                    b.Navigation("ArchivosIE");

                    b.Navigation("ClasesBloquePrograma");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Calificacion", b =>
                {
                    b.Navigation("VersionesSiguientes");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.ClaseDictada", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Curricula", b =>
                {
                    b.Navigation("EspaciosCurriculares");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Curso", b =>
                {
                    b.Navigation("DetallesCursado");

                    b.Navigation("EspaciosCurriculares");

                    b.Navigation("Horarios");

                    b.Navigation("PreceptoresCursos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Division", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Docente", b =>
                {
                    b.Navigation("DocentesEspaciosCurriculares");

                    b.Navigation("EspaciosCurriculares");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.EspacioCurricular", b =>
                {
                    b.Navigation("ClasesDictadas");

                    b.Navigation("DocentesEspaciosCurriculares");

                    b.Navigation("Horarios");

                    b.Navigation("InstanciasEvaluativas");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Estudiante", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("AsistenciasPorEspacio");

                    b.Navigation("Calificaciones");

                    b.Navigation("DetallesCursado");

                    b.Navigation("RetirosAnticipados");

                    b.Navigation("TutorEstudiantes");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.EventoInstitucional", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Horario", b =>
                {
                    b.Navigation("ClasesDictadas");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.InstanciaEvaluativa", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Planificacion", b =>
                {
                    b.Navigation("ClasesBloquePrograma");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Preceptor", b =>
                {
                    b.Navigation("Cursos");

                    b.Navigation("PreceptoresCursos");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Programa", b =>
                {
                    b.Navigation("Objetivos");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Tutor", b =>
                {
                    b.Navigation("RetirosAnticipados");

                    b.Navigation("TutorEstudiantes");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Unidad", b =>
                {
                    b.Navigation("Temas");
                });

            modelBuilder.Entity("TesisGestorApi.Entities.Usuario", b =>
                {
                    b.Navigation("Docente");

                    b.Navigation("Preceptor");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
