// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesisGestorApi.Data;

#nullable disable

namespace TesisGestorApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RepoDB.Entities.Anio", b =>
                {
                    b.Property<Guid>("IdAnio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("IdAnio");

                    b.ToTable("Anios");
                });

            modelBuilder.Entity("RepoDB.Entities.Asistencia", b =>
                {
                    b.Property<Guid>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EstudianteIdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaAsistencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdTipoAsistencia")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoAsistenciaIdTipo")
                        .HasColumnType("uuid");

                    b.Property<int>("Turno")
                        .HasColumnType("integer");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.HasIndex("TipoAsistenciaIdTipo");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("RepoDB.Entities.AsistenciaPorEspacio", b =>
                {
                    b.Property<Guid>("IdAsistenciaEspacio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurriculaIdCurricula")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EstudianteIdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaAsistencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdCurricula")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdTipoAsistencia")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoAsistenciaIdTipo")
                        .HasColumnType("uuid");

                    b.HasKey("IdAsistenciaEspacio");

                    b.HasIndex("CurriculaIdCurricula");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.HasIndex("TipoAsistenciaIdTipo");

                    b.ToTable("AsistenciasPorEspacio");
                });

            modelBuilder.Entity("RepoDB.Entities.CredencialQR", b =>
                {
                    b.Property<Guid>("IdQR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AñoLectivo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Codigo")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enviado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EstudianteIdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.HasKey("IdQR");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.ToTable("CredencialesQR");
                });

            modelBuilder.Entity("RepoDB.Entities.Curricula", b =>
                {
                    b.Property<Guid>("IdCurricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CursoIdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocenteIdDocente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EspacioCurricularIdEC")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HorarioIdHorario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdDocente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEspacioCurricular")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdHorario")
                        .HasColumnType("uuid");

                    b.HasKey("IdCurricula");

                    b.HasIndex("CursoIdCurso");

                    b.HasIndex("DocenteIdDocente");

                    b.HasIndex("EspacioCurricularIdEC");

                    b.HasIndex("HorarioIdHorario");

                    b.ToTable("Curriculas");
                });

            modelBuilder.Entity("RepoDB.Entities.Curso", b =>
                {
                    b.Property<Guid>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnioIdAnio")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AñoLectivo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DivisionIdDivision")
                        .HasColumnType("uuid");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdAnio")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdDivision")
                        .HasColumnType("uuid");

                    b.HasKey("IdCurso");

                    b.HasIndex("AnioIdAnio");

                    b.HasIndex("DivisionIdDivision");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("RepoDB.Entities.DetalleCursado", b =>
                {
                    b.Property<Guid>("IdCursado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CursoIdCurso")
                        .HasColumnType("uuid");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EstudianteIdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.HasKey("IdCursado");

                    b.HasIndex("CursoIdCurso");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.ToTable("DetallesCursado");
                });

            modelBuilder.Entity("RepoDB.Entities.Division", b =>
                {
                    b.Property<Guid>("IdDivision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<char>("Nombre")
                        .HasColumnType("character(1)");

                    b.HasKey("IdDivision");

                    b.ToTable("Divisiones");
                });

            modelBuilder.Entity("RepoDB.Entities.Docente", b =>
                {
                    b.Property<Guid>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDocente");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("RepoDB.Entities.EspacioCurricular", b =>
                {
                    b.Property<Guid>("IdEC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsContraturno")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEC");

                    b.ToTable("EspaciosCurriculares");
                });

            modelBuilder.Entity("RepoDB.Entities.Estudiante", b =>
                {
                    b.Property<Guid>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.HasKey("IdEstudiante");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("RepoDB.Entities.Horario", b =>
                {
                    b.Property<Guid>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CursoIdCurso")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HorarioEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HorarioSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.HasKey("IdHorario");

                    b.HasIndex("CursoIdCurso");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("RepoDB.Entities.Preceptor", b =>
                {
                    b.Property<Guid>("IdPreceptor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CursoIdCurso")
                        .HasColumnType("uuid");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPreceptor");

                    b.HasIndex("CursoIdCurso");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Preceptores");
                });

            modelBuilder.Entity("RepoDB.Entities.RetiroAnticipado", b =>
                {
                    b.Property<Guid>("IdRetiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ConReingreso")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EstudianteIdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("HorarioReingreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HorarioRetiro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdAsistencia")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdTutor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorIdTutor")
                        .HasColumnType("uuid");

                    b.HasKey("IdRetiro");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.HasIndex("IdAsistencia")
                        .IsUnique();

                    b.HasIndex("TutorIdTutor");

                    b.ToTable("RetirosAnticipados");
                });

            modelBuilder.Entity("RepoDB.Entities.Rol", b =>
                {
                    b.Property<Guid>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RepoDB.Entities.TipoAsistencia", b =>
                {
                    b.Property<Guid>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ValorAsistenciaMañana")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorAsistenciaTarde")
                        .HasColumnType("numeric");

                    b.HasKey("IdTipo");

                    b.ToTable("TiposAsistencia");
                });

            modelBuilder.Entity("RepoDB.Entities.Tutor", b =>
                {
                    b.Property<Guid>("IdTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelacionEstudiante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Telefono")
                        .HasColumnType("integer");

                    b.HasKey("IdTutor");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("RepoDB.Entities.TutorEstudiante", b =>
                {
                    b.Property<Guid>("IdTutor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uuid");

                    b.HasKey("IdTutor", "IdEstudiante");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("TutorEstudiante");
                });

            modelBuilder.Entity("RepoDB.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Verificado")
                        .HasColumnType("boolean");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RepoDB.Entities.UsuarioRol", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uuid");

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("RepoDB.Entities.Asistencia", b =>
                {
                    b.HasOne("RepoDB.Entities.Estudiante", "Estudiante")
                        .WithMany("Asistencias")
                        .HasForeignKey("EstudianteIdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.TipoAsistencia", "TipoAsistencia")
                        .WithMany()
                        .HasForeignKey("TipoAsistenciaIdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("TipoAsistencia");
                });

            modelBuilder.Entity("RepoDB.Entities.AsistenciaPorEspacio", b =>
                {
                    b.HasOne("RepoDB.Entities.Curricula", "Curricula")
                        .WithMany("AsistenciasPorEspacio")
                        .HasForeignKey("CurriculaIdCurricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.Estudiante", "Estudiante")
                        .WithMany("AsistenciasPorEspacio")
                        .HasForeignKey("EstudianteIdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.TipoAsistencia", "TipoAsistencia")
                        .WithMany()
                        .HasForeignKey("TipoAsistenciaIdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curricula");

                    b.Navigation("Estudiante");

                    b.Navigation("TipoAsistencia");
                });

            modelBuilder.Entity("RepoDB.Entities.CredencialQR", b =>
                {
                    b.HasOne("RepoDB.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteIdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("RepoDB.Entities.Curricula", b =>
                {
                    b.HasOne("RepoDB.Entities.Curso", "Curso")
                        .WithMany("Curriculas")
                        .HasForeignKey("CursoIdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.Docente", "Docente")
                        .WithMany("Curriculas")
                        .HasForeignKey("DocenteIdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.EspacioCurricular", "EspacioCurricular")
                        .WithMany("Curriculas")
                        .HasForeignKey("EspacioCurricularIdEC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.Horario", "Horario")
                        .WithMany("Curriculas")
                        .HasForeignKey("HorarioIdHorario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Docente");

                    b.Navigation("EspacioCurricular");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("RepoDB.Entities.Curso", b =>
                {
                    b.HasOne("RepoDB.Entities.Anio", "Anio")
                        .WithMany("Cursos")
                        .HasForeignKey("AnioIdAnio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.Division", "Division")
                        .WithMany("Cursos")
                        .HasForeignKey("DivisionIdDivision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anio");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("RepoDB.Entities.DetalleCursado", b =>
                {
                    b.HasOne("RepoDB.Entities.Curso", "Curso")
                        .WithMany("DetallesCursado")
                        .HasForeignKey("CursoIdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.Estudiante", "Estudiante")
                        .WithMany("DetallesCursado")
                        .HasForeignKey("EstudianteIdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("RepoDB.Entities.Docente", b =>
                {
                    b.HasOne("RepoDB.Entities.Usuario", "Usuario")
                        .WithOne("Docente")
                        .HasForeignKey("RepoDB.Entities.Docente", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RepoDB.Entities.Horario", b =>
                {
                    b.HasOne("RepoDB.Entities.Curso", "Curso")
                        .WithMany("Horarios")
                        .HasForeignKey("CursoIdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("RepoDB.Entities.Preceptor", b =>
                {
                    b.HasOne("RepoDB.Entities.Curso", "Curso")
                        .WithMany("Preceptores")
                        .HasForeignKey("CursoIdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.Usuario", "Usuario")
                        .WithOne("Preceptor")
                        .HasForeignKey("RepoDB.Entities.Preceptor", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RepoDB.Entities.RetiroAnticipado", b =>
                {
                    b.HasOne("RepoDB.Entities.Estudiante", "Estudiante")
                        .WithMany("RetirosAnticipados")
                        .HasForeignKey("EstudianteIdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.Asistencia", "Asistencia")
                        .WithOne("RetiroAnticipado")
                        .HasForeignKey("RepoDB.Entities.RetiroAnticipado", "IdAsistencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.Tutor", "Tutor")
                        .WithMany("RetirosAnticipados")
                        .HasForeignKey("TutorIdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asistencia");

                    b.Navigation("Estudiante");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("RepoDB.Entities.TutorEstudiante", b =>
                {
                    b.HasOne("RepoDB.Entities.Estudiante", "Estudiante")
                        .WithMany("TutorEstudiantes")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.Tutor", "Tutor")
                        .WithMany("TutorEstudiantes")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("RepoDB.Entities.UsuarioRol", b =>
                {
                    b.HasOne("RepoDB.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoDB.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RepoDB.Entities.Anio", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("RepoDB.Entities.Asistencia", b =>
                {
                    b.Navigation("RetiroAnticipado");
                });

            modelBuilder.Entity("RepoDB.Entities.Curricula", b =>
                {
                    b.Navigation("AsistenciasPorEspacio");
                });

            modelBuilder.Entity("RepoDB.Entities.Curso", b =>
                {
                    b.Navigation("Curriculas");

                    b.Navigation("DetallesCursado");

                    b.Navigation("Horarios");

                    b.Navigation("Preceptores");
                });

            modelBuilder.Entity("RepoDB.Entities.Division", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("RepoDB.Entities.Docente", b =>
                {
                    b.Navigation("Curriculas");
                });

            modelBuilder.Entity("RepoDB.Entities.EspacioCurricular", b =>
                {
                    b.Navigation("Curriculas");
                });

            modelBuilder.Entity("RepoDB.Entities.Estudiante", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("AsistenciasPorEspacio");

                    b.Navigation("DetallesCursado");

                    b.Navigation("RetirosAnticipados");

                    b.Navigation("TutorEstudiantes");
                });

            modelBuilder.Entity("RepoDB.Entities.Horario", b =>
                {
                    b.Navigation("Curriculas");
                });

            modelBuilder.Entity("RepoDB.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("RepoDB.Entities.Tutor", b =>
                {
                    b.Navigation("RetirosAnticipados");

                    b.Navigation("TutorEstudiantes");
                });

            modelBuilder.Entity("RepoDB.Entities.Usuario", b =>
                {
                    b.Navigation("Docente");

                    b.Navigation("Preceptor");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
